import type { Scenario } from './types';

const hypoglycemia: Scenario = {
  id: 'hypoglycemia',
  title: 'Hypoglycemia',
  subtitle: 'Post-op diabetic patient who is shaky, sweaty and confused',
  difficulty: 'Beginner',
  patient: {
    name: 'Maria Santos',
    age: 62,
    sex: 'F',
    dob: '03/14/1964',
    mrn: 'MRN 204-5518',
    room: '304',
    diagnosis: 'POD #1 right total knee arthroplasty; Type 2 diabetes mellitus',
    allergies: 'Penicillin (rash)',
    history: ['Type 2 DM on basal-bolus insulin', 'Hypertension', 'Osteoarthritis'],
    orders: [
      'Insulin glargine 20 units SubQ at bedtime',
      'Insulin lispro 6 units SubQ with meals + sliding scale',
      'Hypoglycemia protocol: BG < 70 mg/dL & able to swallow → 15 g fast-acting carbs, recheck in 15 min. Unable to swallow → D50W 25 mL IV or glucagon 1 mg IM',
      'Capillary blood glucose AC & HS and PRN symptoms',
      'Vital signs q4h',
    ],
    handoff:
      'Received lispro 6 units with breakfast about an hour ago but only ate a few bites; she was nauseated after her pain medication. The nursing aide just said she is "acting strange and sweaty."',
  },
  stableVitals: { hr: 78, sbp: 128, dbp: 78, rr: 16, spo2: 98, temp: 36.8 },
  crashVitals: { hr: 132, sbp: 92, dbp: 54, rr: 24, spo2: 93, temp: 36.1 },
  startSeverity: 0.35,
  drift: 1 / 210,
  skinTone: 'pale',
  patientLines: {
    mild: '"I feel... shaky. Why am I so sweaty? Where... where am I again?" (She is tremulous and diaphoretic but follows commands and can swallow.)',
    severe: '(She mumbles incoherently, eyes half closed, skin cold and clammy. She is barely able to follow commands.)',
    recovered: '"Oh, I feel so much better. I guess I should have eaten more of my breakfast."',
  },
  bloodGlucose: { start: 48, afterTreatment: 94 },
  lungSounds: 'Clear bilaterally in all lobes.',
  outcomes: {
    hand_hygiene: {
      kind: 'critical', points: 10,
      feedback: 'Hands sanitized. Ready for patient contact.',
      rationale: 'Hand hygiene before patient contact prevents healthcare-associated infections, and she has a fresh surgical wound.',
    },
    verify_id: {
      kind: 'critical', points: 10,
      feedback: 'Wristband confirms: Maria Santos, DOB 03/14/1964. Allergy band: PENICILLIN.',
      rationale: 'Two identifiers are required before any treatment or medication.',
    },
    talk: {
      kind: 'good', points: 5, feedback: '',
      rationale: 'Confusion, tremors, diaphoresis and tachycardia are classic adrenergic and neuroglycopenic signs of hypoglycemia.',
    },
    check_glucose: {
      kind: 'critical', points: 15,
      feedback: 'Fingerstick glucose: 48 mg/dL (critical LOW).',
      rationale: 'Confirm suspected hypoglycemia with a point-of-care glucose. BG < 70 mg/dL is hypoglycemia; < 54 mg/dL is clinically significant.',
    },
    oral_glucose: {
      kind: 'critical', points: 20, severityDelta: -0.2, driftMultiplier: 0,
      requires: ['check_glucose'],
      blockedFeedback: 'Confirm the suspected hypoglycemia with a fingerstick first. It takes 30 seconds and the glucometer is on the bedside table.',
      feedback: 'She drinks 4 oz of orange juice without difficulty. Swallow intact.',
      rationale: 'Rule of 15: a conscious patient who can swallow gets 15 g of fast-acting carbs by mouth first. It is the least invasive and fastest route.',
    },
    med_dextrose: {
      kind: 'good', points: 8, severityDelta: -0.3, driftMultiplier: 0,
      requires: ['check_glucose'],
      blockedFeedback: 'Check the blood glucose before giving IV dextrose.',
      feedback: 'D50W 25 mL pushed via IV. She perks up within minutes.',
      rationale: 'D50W works, but it is reserved for patients who cannot safely swallow. She could take oral carbs, which is the less invasive option.',
    },
    med_glucagon: {
      kind: 'good', points: 6, severityDelta: -0.25, driftMultiplier: 0,
      requires: ['check_glucose'],
      blockedFeedback: 'Check the blood glucose before giving glucagon.',
      feedback: 'Glucagon 1 mg IM given. Onset takes 10–15 minutes. Watch for nausea and vomiting.',
      rationale: 'Glucagon is for patients who cannot swallow and have no IV access. She could swallow, so oral carbs were preferred.',
    },
    recheck_glucose: {
      kind: 'critical', points: 15, severityDelta: -0.15,
      requires: [['oral_glucose', 'med_dextrose', 'med_glucagon']],
      blockedFeedback: 'Treat the low glucose first, then recheck in 15 minutes.',
      feedback: '15 minutes later: BG 94 mg/dL. She is alert and oriented ×4.',
      rationale: 'Recheck 15 minutes after treatment. If BG is still < 70 mg/dL, repeat 15 g of carbs.',
    },
    give_snack: {
      kind: 'good', points: 8,
      requires: ['recheck_glucose'],
      blockedFeedback: 'Give fast-acting carbs first. Save the protein snack for after the glucose is back above 70.',
      feedback: 'She eats crackers with peanut butter.',
      rationale: 'Once BG > 70, give a snack with complex carbs and protein if the next meal is more than 1 hour away. This prevents a rebound low.',
    },
    med_insulin: {
      kind: 'harmful', points: -30, severityDelta: 0.35,
      feedback: 'Insulin administered. Within minutes she becomes unresponsive and diaphoretic.',
      rationale: 'NEVER give insulin to a hypoglycemic patient. It drives glucose even lower and can cause seizures and death.',
    },
    attach_monitor: {
      kind: 'good', points: 4,
      feedback: 'Monitor on: sinus tachycardia.',
      rationale: 'Tachycardia is a compensatory adrenergic response to hypoglycemia.',
    },
    read_vitals: { kind: 'good', points: 4, feedback: '', rationale: 'Tachycardia and diaphoresis come from the catecholamine surge during hypoglycemia.' },
    call_provider: {
      kind: 'good', points: 8,
      feedback: 'SBAR given. Provider orders: hold next lispro dose, reduce glargine to 16 units, dietitian consult.',
      rationale: 'Notify the provider after treating. Insulin doses usually need adjusting when oral intake is poor.',
    },
    document: {
      kind: 'good', points: 5,
      feedback: 'Documented the hypoglycemic event, treatment, recheck and response.',
      rationale: 'Document the BG values, treatment given, time of recheck and patient response.',
    },
    call_rrt: {
      kind: 'neutral', points: 0,
      feedback: 'The RRT arrives. She is conscious with a patent airway, and the hypoglycemia protocol covers her treatment.',
      rationale: 'RRT is appropriate if the patient becomes unresponsive or seizes. A conscious hypoglycemic patient is managed with the nurse-driven protocol.',
    },
    leave_room: {
      kind: 'harmful', points: -15, severityDelta: 0.1,
      feedback: 'While you were out, she tried to get up and nearly fell.',
      rationale: 'Never leave a confused, hypoglycemic post-op patient alone. They are a high fall risk. Use the call light to get supplies brought to you.',
    },
    o2_nrb: {
      kind: 'neutral', points: -3,
      feedback: 'SpO₂ was already 97–98%. High-flow O₂ is not indicated.',
      rationale: 'Oxygen is a drug. Titrate it to the SpO₂ target.',
    },
  },
  criticalPath: ['hand_hygiene', 'verify_id', 'check_glucose', ['oral_glucose', 'med_dextrose', 'med_glucagon'], 'recheck_glucose'],
  debriefPearls: [
    'Rule of 15: 15 g fast-acting carbs → recheck in 15 min → repeat if BG < 70 mg/dL.',
    'Route depends on the patient: can swallow → oral; cannot swallow with IV access → D50W; no IV access → glucagon IM/SubQ/intranasal.',
    'Signs of hypoglycemia: shaky, sweaty, tachycardic, anxious, confused ("cold & clammy, need some candy").',
    'After recovery, give a complex carb + protein snack and find the cause (e.g. insulin given, but the meal was not eaten).',
  ],
};

const heartFailure: Scenario = {
  id: 'pulmonary-edema',
  title: 'Acute Pulmonary Edema',
  subtitle: 'Heart-failure patient in sudden respiratory distress',
  difficulty: 'Intermediate',
  patient: {
    name: 'Roberto Cruz',
    age: 74,
    sex: 'M',
    dob: '07/22/1952',
    mrn: 'MRN 331-0927',
    room: '304',
    diagnosis: 'Community-acquired pneumonia; chronic HFrEF (EF 30%)',
    allergies: 'No known drug allergies',
    history: ['Heart failure with reduced EF (30%)', 'Coronary artery disease, CABG 2018', 'CKD stage 3', 'Type 2 DM (diet-controlled)'],
    orders: [
      '0.9% NaCl at 125 mL/hr (started on admission)',
      'Furosemide 40 mg IV push PRN for signs of fluid overload. Notify provider',
      'Oxygen to keep SpO₂ ≥ 92%',
      'Strict I&O, daily weight',
      'Ceftriaxone 1 g IV daily, azithromycin 500 mg IV daily',
    ],
    handoff:
      'Admitted overnight for pneumonia. He has had NS at 125 mL/hr for 14 hours and is +2.1 L. His call light just went on and he is sitting on the edge of the bed gasping.',
  },
  stableVitals: { hr: 88, sbp: 136, dbp: 82, rr: 18, spo2: 95, temp: 37.4 },
  crashVitals: { hr: 142, sbp: 188, dbp: 112, rr: 38, spo2: 72, temp: 37.6 },
  startSeverity: 0.45,
  drift: 1 / 170,
  skinTone: 'cyanotic',
  patientLines: {
    mild: '"I... can\'t... catch... my breath." (Speaking in 2–3 word phrases, anxious, coughing pink frothy sputum. He is fighting to sit upright.)',
    severe: '(Gasping, too breathless to speak. Lips dusky, skin cool and diaphoretic.)',
    recovered: '"That\'s better... I can breathe again. I\'ve been going to the bathroom a lot, though!"',
  },
  lungSounds: 'Coarse crackles bilaterally up to the mid-lung fields, with an S3 gallop. Jugular veins distended at 45°.',
  outcomes: {
    hand_hygiene: {
      kind: 'critical', points: 10,
      feedback: 'Hands sanitized.',
      rationale: 'Hand hygiene takes seconds and is expected even in urgent situations.',
    },
    verify_id: {
      kind: 'critical', points: 8,
      feedback: 'Wristband confirms: Roberto Cruz, DOB 07/22/1952. NKDA.',
      rationale: 'Two identifiers are required before giving medications, even in an emergency.',
    },
    talk: { kind: 'good', points: 4, feedback: '', rationale: 'Speaking in 2–3 word phrases is a sign of severe respiratory distress.' },
    assess_lungs: {
      kind: 'good', points: 8, feedback: '',
      rationale: 'Bilateral crackles, S3, JVD and pink frothy sputum after a positive fluid balance point to acute cardiogenic pulmonary edema.',
    },
    hob_high: {
      kind: 'critical', points: 15, severityDelta: -0.06, driftMultiplier: 0.75,
      feedback: "HOB raised to High Fowler's with legs dependent. His breathing is slightly easier.",
      rationale: "High Fowler's with legs dangling reduces venous return (preload) and improves lung expansion. It is the first, free intervention.",
    },
    position_flat: {
      kind: 'harmful', points: -20, severityDelta: 0.2,
      feedback: 'Lying flat, he becomes more panicked and his SpO₂ falls rapidly.',
      rationale: 'Lying flat increases venous return and worsens pulmonary congestion (orthopnea). Never lay a patient in pulmonary edema flat.',
    },
    legs_up: {
      kind: 'harmful', points: -20, severityDelta: 0.2,
      feedback: 'With legs elevated, fluid shifts centrally and his distress worsens.',
      rationale: 'Elevating the legs increases preload, the opposite of what a fluid-overloaded heart needs.',
    },
    o2_nrb: {
      kind: 'critical', points: 15, severityDelta: -0.08, driftMultiplier: 0.7,
      feedback: 'Non-rebreather at 15 L/min. SpO₂ starts climbing.',
      rationale: 'SpO₂ in the 80s with severe distress needs high-flow oxygen right away. Titrate down to the target (≥ 92%) once stable.',
    },
    o2_nc: {
      kind: 'good', points: 3, severityDelta: -0.02,
      feedback: 'Nasal cannula at 2 L/min. SpO₂ barely changes (87–88%). This is not enough.',
      rationale: 'Low-flow nasal cannula is inadequate for severe hypoxemia. Escalate to a non-rebreather.',
    },
    stop_infusion: {
      kind: 'critical', points: 15, driftMultiplier: 0.75,
      feedback: 'NS infusion stopped. Line kept saline-locked for IV access.',
      rationale: 'Stop the fluid that is causing the overload, but keep the IV access for medications.',
    },
    resume_infusion: {
      kind: 'harmful', points: -20, severityDelta: 0.15,
      feedback: 'More fluid is going into an already overloaded circulation. Crackles worsen.',
      rationale: 'In fluid-volume excess, stop or minimize IV fluids.',
    },
    ns_bolus: {
      kind: 'harmful', points: -30, severityDelta: 0.3,
      feedback: 'A liter of fluid is pouring into a failing heart. He is drowning in his own secretions.',
      rationale: 'A fluid bolus is contraindicated in cardiogenic pulmonary edema.',
    },
    med_furosemide: {
      kind: 'critical', points: 20, severityDelta: -0.15, driftMultiplier: 0.4,
      feedback: 'Furosemide 40 mg IV pushed over 1–2 min. Within 15 min, he voids 600 mL.',
      rationale: 'The loop diuretic reduces preload and pulmonary congestion. Push slowly (≤ 20 mg/min, ototoxicity) and monitor K⁺, BP and urine output.',
    },
    call_provider: {
      kind: 'critical', points: 12,
      feedback: 'SBAR given. Provider orders: stop NS, chest X-ray, BNP, BMP, repeat furosemide in 2 hr if needed, strict I&O.',
      rationale: 'An acute change in respiratory status needs immediate SBAR communication. PRN furosemide orders say "notify provider".',
    },
    call_rrt: {
      kind: 'good', points: 6,
      feedback: 'The RRT arrives to help. Respiratory therapy sets up for possible BiPAP.',
      rationale: 'Calling the RRT for acute respiratory distress is appropriate and never wrong when you are worried.',
    },
    attach_monitor: {
      kind: 'good', points: 5,
      feedback: 'Monitor on: sinus tachycardia with occasional PVCs.',
      rationale: 'Continuous monitoring catches dysrhythmias, which are common in decompensated HF and with electrolyte shifts from diuresis.',
    },
    read_vitals: { kind: 'good', points: 4, feedback: '', rationale: 'Tachycardia, tachypnea, hypertension and hypoxemia fit acute decompensated HF.' },
    document: {
      kind: 'good', points: 5,
      feedback: 'Documented respiratory assessment, interventions, I&O and response.',
      rationale: 'Document lung sounds, SpO₂ trend, urine output and daily weight.',
    },
    leave_room: {
      kind: 'harmful', points: -15, severityDelta: 0.12,
      feedback: 'He is alone and struggling to breathe while you are out.',
      rationale: 'Never leave a patient in respiratory distress. Call for help from the bedside.',
    },
    check_glucose: {
      kind: 'neutral', points: 0,
      feedback: 'BG 142 mg/dL.',
      rationale: 'Glucose is reasonable in a diabetic patient but not the priority in respiratory distress (Airway, Breathing first).',
    },
    med_insulin: {
      kind: 'harmful', points: -10,
      feedback: 'Insulin given without a glucose check or indication.',
      rationale: 'This patient is diet-controlled and was not due for insulin.',
    },
  },
  criticalPath: ['hand_hygiene', 'verify_id', 'hob_high', 'o2_nrb', 'stop_infusion', 'call_provider', 'med_furosemide'],
  debriefPearls: [
    'Positioning: High Fowler\'s with legs dependent reduces preload and is the first thing to do.',
    'Remember "UNLOAD FAST": Upright, Nitrates, Lasix, Oxygen, ACE-I, Digoxin, Fluids (restrict), Afterload reduction, Sodium restriction, Test (BNP, CXR, electrolytes).',
    'Loop diuretics: monitor potassium (hypokalemia → dysrhythmias), BP and urine output; push IV furosemide ≤ 20 mg/min.',
    'Pink frothy sputum + crackles + S3 = pulmonary edema, a medical emergency.',
  ],
};

const anaphylaxis: Scenario = {
  id: 'anaphylaxis',
  title: 'Anaphylaxis',
  subtitle: 'Allergic reaction minutes after an IV antibiotic starts',
  difficulty: 'Advanced',
  patient: {
    name: 'Ana Reyes',
    age: 34,
    sex: 'F',
    dob: '11/02/1991',
    mrn: 'MRN 417-2260',
    room: '304',
    diagnosis: 'Cellulitis, left lower leg',
    allergies: 'Amoxicillin (hives, as a child)',
    history: ['Asthma, mild intermittent', 'No prior hospitalizations'],
    orders: [
      'Ceftriaxone 1 g IV q24h (first dose infusing)',
      'Anaphylaxis protocol: epinephrine 0.5 mg IM (1 mg/mL) anterolateral thigh, may repeat q5–15 min',
      'Oxygen to keep SpO₂ ≥ 94%',
      '0.9% NaCl 1 L bolus for hypotension (SBP < 90)',
      'Diphenhydramine 50 mg IV PRN (adjunct)',
    ],
    handoff:
      'First dose of IV ceftriaxone started 10 minutes ago. She pressed the call light saying "something is wrong."',
  },
  stableVitals: { hr: 86, sbp: 118, dbp: 74, rr: 16, spo2: 98, temp: 37.9 },
  crashVitals: { hr: 152, sbp: 58, dbp: 30, rr: 34, spo2: 76, temp: 37.9 },
  startSeverity: 0.5,
  drift: 1 / 130,
  skinTone: 'flushed',
  patientLines: {
    mild: '"My throat feels tight... I\'m itchy all over... I feel like something terrible is happening." (Hives on the chest and neck, lips swelling, audible wheeze.)',
    severe: '(Hoarse, stridorous breathing. She can barely speak. Skin mottled, lips and tongue swollen.)',
    recovered: '"The itching is better and I can swallow again. That was terrifying."',
  },
  lungSounds: 'Diffuse expiratory wheezes bilaterally with inspiratory stridor over the neck.',
  outcomes: {
    stop_infusion: {
      kind: 'critical', points: 25, severityDelta: -0.05, driftMultiplier: 0.7,
      feedback: 'Ceftriaxone stopped. Tubing changed and the line kept open with NS. The antibiotic bag is saved for reporting.',
      rationale: 'FIRST: stop the suspected trigger immediately. Keep IV access, but change the tubing so no more drug is infused.',
    },
    resume_infusion: {
      kind: 'harmful', points: -30, severityDelta: 0.3,
      feedback: 'More ceftriaxone infuses. Her airway is closing.',
      rationale: 'Continuing the offending drug worsens anaphylaxis and can be fatal.',
    },
    call_rrt: {
      kind: 'critical', points: 15,
      feedback: 'Rapid Response called. The team is on the way with the airway cart.',
      rationale: 'Anaphylaxis with airway compromise and hypotension is a medical emergency. Call for help early and stay with the patient.',
    },
    med_epi_im: {
      kind: 'critical', points: 25, severityDelta: -0.25, driftMultiplier: 0.3,
      feedback: 'Epinephrine 0.5 mg IM in the anterolateral thigh. Within minutes, wheezing eases and BP starts to rise.',
      rationale: 'IM epinephrine (1 mg/mL) in the anterolateral thigh is THE first-line drug for anaphylaxis. Do not delay it for antihistamines.',
    },
    med_epi_iv: {
      kind: 'harmful', points: -20, severityDelta: 0.1,
      feedback: 'Heart rate spikes to 180 with runs of V-tach. The RRT stops the push.',
      rationale: '1 mg IV push epinephrine is a cardiac-arrest dose. A patient in anaphylaxis with a pulse gets IM epinephrine.',
    },
    o2_nrb: {
      kind: 'critical', points: 12, severityDelta: -0.06, driftMultiplier: 0.85,
      feedback: 'Non-rebreather at 15 L/min.',
      rationale: 'Support oxygenation with high-flow O₂ during airway compromise.',
    },
    o2_nc: {
      kind: 'good', points: 3, severityDelta: -0.01,
      feedback: 'Nasal cannula 2 L/min. SpO₂ stays low. Escalate.',
      rationale: 'Low-flow O₂ is insufficient for a compromised airway.',
    },
    ns_bolus: {
      kind: 'critical', points: 12, severityDelta: -0.12,
      requires: ['stop_infusion'],
      blockedFeedback: 'The ceftriaxone is still running through that line! Stop the offending drug first.',
      feedback: 'NS 1 L bolus running wide open through new tubing. BP improving.',
      rationale: 'Anaphylaxis causes massive vasodilation and capillary leak (distributive shock). Rapid isotonic fluids restore perfusion.',
    },
    legs_up: {
      kind: 'good', points: 5, severityDelta: -0.03,
      feedback: 'Flat with legs raised. BP improves slightly, but breathing feels harder.',
      rationale: 'Hypotension → supine with legs elevated. With airway or breathing difficulty, a position of comfort (semi-sitting) may be needed. Balance the two.',
    },
    hob_high: {
      kind: 'good', points: 4,
      feedback: 'Sitting up eases her breathing, but she feels light-headed.',
      rationale: 'Semi-sitting helps breathing, but watch hypotension. Never make a hypotensive anaphylactic patient stand or walk.',
    },
    med_diphen: {
      kind: 'good', points: 4,
      requires: ['med_epi_im'],
      blockedFeedback: 'Antihistamines do NOT reverse airway edema or shock. Give epinephrine first.',
      feedback: 'Diphenhydramine 50 mg IV given as an adjunct. Itching improves.',
      rationale: 'Antihistamines are second-line adjuncts only (they help hives and itching). Epinephrine always comes first.',
    },
    hand_hygiene: {
      kind: 'good', points: 5,
      feedback: 'Hands sanitized.',
      rationale: 'Hand hygiene takes seconds and is still expected in an emergency.',
    },
    verify_id: {
      kind: 'good', points: 5,
      feedback: 'Wristband: Ana Reyes, DOB 11/02/1991. Allergy band: AMOXICILLIN.',
      rationale: 'The allergy band reveals a penicillin allergy. Cephalosporins carry a small cross-sensitivity risk, and she needed close monitoring during the first dose.',
    },
    talk: { kind: 'good', points: 3, feedback: '', rationale: 'Throat tightness, hoarseness and stridor mean impending airway obstruction.' },
    assess_lungs: { kind: 'good', points: 5, feedback: '', rationale: 'Wheezing and stridor indicate bronchospasm and upper-airway edema.' },
    attach_monitor: { kind: 'good', points: 5, feedback: 'Monitor on: sinus tachycardia.', rationale: 'Continuous monitoring is essential; epinephrine can also cause dysrhythmias.' },
    read_vitals: { kind: 'good', points: 3, feedback: '', rationale: 'Hypotension + tachycardia + hypoxemia = anaphylactic shock.' },
    call_provider: {
      kind: 'good', points: 6,
      feedback: 'Provider notified. Orders: methylprednisolone 125 mg IV, famotidine 20 mg IV, observe at least 6 hr for biphasic reaction, update allergy list.',
      rationale: 'Notify the provider, and update the allergy record so the drug is never given again.',
    },
    document: {
      kind: 'good', points: 5,
      feedback: 'Reaction, interventions and response documented. Allergy list updated; incident/ADR report filed.',
      rationale: 'Document the reaction, update the allergy list, and file an adverse drug reaction report.',
    },
    position_flat: {
      kind: 'neutral', points: 0,
      feedback: 'Lying flat. BP is supported a little, but breathing feels tighter.',
      rationale: 'Flat with legs raised helps perfusion better.',
    },
    leave_room: {
      kind: 'harmful', points: -20, severityDelta: 0.15,
      feedback: 'Her airway is swelling shut while you are away.',
      rationale: 'Never leave a patient with a threatened airway. Call for help and have the crash cart brought to you.',
    },
  },
  criticalPath: ['stop_infusion', 'call_rrt', 'med_epi_im', 'o2_nrb', 'ns_bolus'],
  debriefPearls: [
    'Priority order: STOP the trigger → call for help → EPINEPHRINE IM → airway/O₂ → fluids → adjuncts.',
    'Epinephrine 0.5 mg IM (adult) of 1 mg/mL into the anterolateral thigh; may repeat every 5–15 min.',
    'Antihistamines and steroids are adjuncts. They do not treat airway obstruction or shock.',
    'Watch for a biphasic reaction (return of symptoms hours later). Observe for at least 4–6 hours.',
    'A penicillin allergy history needs close monitoring when giving cephalosporins, especially the first dose.',
  ],
};

export const SCENARIOS: Scenario[] = [hypoglycemia, heartFailure, anaphylaxis];
